name: Deploy Wheel Frontend

on:
  workflow_call:
    secrets:
      user:
        required: true
      host:
        required: true
      private_key:
        required: true


jobs:
  deploy_fe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.10.0 ]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install and npm run build
        run: |
          npm i
          npm run build
          echo ${{ github.ref_name }} >> ./dist/test.md
          echo ${{ github.sha }} >> ./dist/test.md

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.private_key }}
          known_hosts: 'fake-placeholder'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.host }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.user }}@${{ secrets.host }}:/home/aist/preprod/test-cd
