name: Deploy Wheel Frontend

on:
  workflow_call:
    inputs:
      base_url:
        required: true
        type: string
    secrets:
      user:
        required: true
      host:
        required: true
      private_key:
        required: true


jobs:
  deploy_fe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.10.0 ]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install and npm run build
        run: |
          npm i \
          && npm run build \
          && find ./dist -type f -name 'environment.*' -exec bash -c \
          'echo "interface IEnvironment {" > {} \
          && echo "    code?: string," >> {} \
          && echo "    production: boolean," >> {} \
          && echo "    configEndpoint: string," >> {} \
          && echo "    consultationEndpoint: string," >> {} \
          && echo "    clientEndpoint: string," >> {} \
          && echo "    branch: string," >> {} \
          && echo "    hash: string," >> {} \
          && echo "}" >> {} \
          && echo "" >> {} \
          && echo "export const environment: IEnvironment = {" >> {} \
          && echo "    code: \"wl\"," >> {} \
          && echo "    production: true," >> {} \
          && echo "    configEndpoint: \"https://${{ inputs.base_url }}/client-api/bo/instance\"," >> {} \
          && echo "    consultationEndpoint: \"https://${{ inputs.base_url }}/client-api/bo/consultations\"," >> {} \
          && echo "    clientEndpoint: \"https://${{ inputs.base_url }}/client-api\"," >> {} \
          && echo "    branch: \"${{ github.ref_name }}\"," >> {} \
          && echo "    hash: \"${{ github.sha }}\"," >> {} \
          && echo "}" >> {}' \; \
          && find ./dist -type f -name 'environment.*' -exec cat {} +

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.private_key }}
          known_hosts: 'fake-placeholder'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.host }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.user }}@${{ secrets.host }}:/home/aist/preprod/test-cd
